### ISSUE TITLE
Microsoft Edge Add-ons API is released

### ISSUE THREAD

**Issue by p0we7** [cardinalby/webext-buildtools-chrome-webstore-builder#4]
detail on https://github.com/MicrosoftDocs/edge-developer/issues/900#issuecomment-899388023

Any consideration of support, please?

**Comment by cardinalby** [comment]
Hi! I'm not sure I have enough capacity to handle it by myself at the moment but will take a look. Any help and contribution are appreciated!

Also, as I understood from the comments, Publishing API isn't available yet.
